# æœºå™¨äººé…ç½®æ–‡ä»¶
BotInformation: {
  token: "1/MTYzODY=/iF8WZej2HqHXBoORGU6OIA==",
}
# ç»éªŒå€¼é…ç½®æ–‡ä»¶
Experience: {
  level-0: 0,
  level-1: 5,
  level-2: 10,
  level-3: 20,
  level-4: 40,
  level-5: 80,
  level-6: 160,
  level-7: 320,
  level-8: 640,
  level-9: 1280,
  level-10: 2560,
  level-11: 3840,
  level-12: 5780,
  level-13: 8670,
  level-14: 13005,
  level-15: 19507,
  level-16: 29260,
  level-17: 43890,
  level-18: 65835,
  level-19: 98752,
  level-20: 123440,
  level-21: 154300,
  level-22: 192875,
  level-23: 241093,
  level-24: 301366,
  level-25: 376707,
  level-26: 470883,
  level-27: 588603,
  level-28: 735753,
  level-29: 919691,
  level-30: 1149613,
  level-31: 1437016,
  level-32: 1796270,
  level-33: 2245337,
  level-34: 2806671,
  level-35: 3508338,
  level-36: 4385422,
  level-37: 5481777,
  level-38: 6852221,
  level-39: 8565276,
  level-40: 10706595,
}
# æœºå™¨äººæŒ‡ä»¤é…ç½®æ–‡ä»¶
BotCommand: {
  help: {
    name: "/help",
    context: "æŸ¥è¯¢æŒ‡ä»¤åŠŸèƒ½",
    parameter: "<é¡µæ•°>",
    register_command: "help",
    parameter_number: 1
  },
  shout: {
    name: "/hh ",
    context: "å…¨æœå–Šè¯",
    parameter: "<å–Šè¯å†…å®¹>",
    register_command: "hh",
    parameter_number: 1
  },
  mainCard: {
    name: "/QF",
    context: "æ‰“å¼€æ¸…é£ç¤¾åŒºåŠŸèƒ½é¡µé¢",
    parameter: "",
    register_command: "QF",
    parameter_number: 0
  },
  userInformation: {
    name: "/inf",
    context: "æŸ¥è¯¢ä¸ªäººä¿¡æ¯",
    parameter: "",
    register_command: "inf",
    parameter_number: 0
  },
  voiceSet: {
    name: "/è¯­éŸ³è®¾ç½®",
    context: "å¼€é»‘è¯­éŸ³é¢‘é“è®¾ç½®",
    parameter: "<äººæ•°>",
    register_command: "è¯­éŸ³è®¾ç½®",
    parameter_number: 1
  },
  serverBind: {
    name: "/Gbind",
    context: "ç»‘å®šæ¸¸æˆæœåŠ¡å™¨æŸ¥è¯¢ä¿¡æ¯",
    parameter: "<MCæœåŠ¡å™¨ID> <ç”¨æˆ·token>",
    register_command: "Gbind",
    parameter_number: 2,
  },

}
# å…³äºKOOKæœåŠ¡å™¨é…ç½®ä¿¡æ¯
KookServerSetting: {
  # æœåŠ¡å™¨ç±»
  guild: {
    #æœåŠ¡å™¨ID
    guild_id: "8329917220869199",
    # å…¨æœå–Šè¯è¢«ç¦æ­¢é¢‘é“ï¼ˆåŒ…æ‹¬è¯­éŸ³é¢‘é“å’Œæ–‡å­—é¢‘é“ï¼‰
    stop_server_say: [
      { 'name': 'ğŸš© æ¬¢è¿é¢‘é“', 'id': '7259581131722418' },
      { 'name': 'ğŸ“° ç¤¾åŒºå…¬å‘Š', 'id': '9337880605442554' },
      { 'name': 'ğŸ æ—¥å¸¸æ´»åŠ¨', 'id': '6117277688797923' },
      { 'name': 'ğŸ® ç»„é˜Ÿä¸“åŒº', 'id': '4481485386328544' },
      { 'name': 'ğŸµ å¬æ­Œæˆ¿', 'id': '8033059623947590' },
      { 'name': 'åˆ›å»ºå¼€é»‘æˆ¿é—´', 'id': '6770879098699231' },
      { 'name': 'æœºå™¨äººå®æµ‹', 'id': '5141681337930033' },
      { 'name': 'å®˜æ–¹ç›´æ’­', 'id': '1457478088054362' },
    ]
  },
  # é¢‘é“ç±»
  channel: {
    # æ–‡å­—é¢‘é“
    text_channel: {
      # ç»„é˜Ÿ
      team_up: {
        # ç»„é˜Ÿæ–‡å­—é¢‘é“
        team_up_channel_id: "4481485386328544",
      },
      robot_system_load: "3645986850919298",
    },
    # è¯­éŸ³é¢‘é“
    voice_channel: {
      # ä¸èƒ½ç»„é˜Ÿçš„è¯­éŸ³é¢‘é“
      false_team_up_channel: [
        "1457478088054362",
        "5294965030848411",
        "8033059623947590",
        "6770879098699231" ],
      # åˆ›å»ºç»„é˜Ÿæˆ¿é—´é¢‘é“
      create_team_up_voice_channel: "6770879098699231",
    }
  },
}
# MCæœåŠ¡å™¨API
ServerApi: {
  "28737551": ""
}